# Generated by Django 3.2.9 on 2021-11-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='auth.user')),
                ('token', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
